"""
Django settings for IIHMR project.

Generated by 'django-admin startproject' using Django 4.0.10.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path
import os


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-6)=%2e$i$t*rz)=yj&946*cr@xwdmm8lr$ey0el%ul)^l%p(0j'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

#ALLOW REQUESTED FROM locahost:3000


ALLOWED_HOSTS = ['*']



INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'iihmrapp.apps.IihmrappConfig',
    'corsheaders',
    'django_session_timeout',
]

#MIDDLEWARE = [
#    'django.middleware.security.SecurityMiddleware',
#    'django.contrib.sessions.middleware.SessionMiddleware',
#    'django.middleware.common.CommonMiddleware',
#    'django.middleware.csrf.CsrfViewMiddleware',
#    'django.contrib.auth.middleware.AuthenticationMiddleware',
#    'django.contrib.messages.middleware.MessageMiddleware',
#    'django.middleware.clickjacking.XFrameOptionsMiddleware',
#    'corsheaders.middleware.CorsMiddleware',    
#]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # Move this above CommonMiddleware
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_session_timeout.middleware.SessionTimeoutMiddleware',
]

ROOT_URLCONF = 'IIHMR.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'IIHMR.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME':'iihmr_test',
#         'USER':'dev_user',
#         'PASSWORD': 'Kavin@410',
#         'HOST': '65.1.177.181',
#         'PORT': '3306',
#         'OPTIONS': {
#         'connect_timeout': 28000,  # Increase timeout to 28 seconds            
#         'sql_mode': 'traditional',
#         'init_command': 'ALTER DATABASE iihmr_test CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci',
#         },
#     }
# }


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME':'iihmr_live',
        'USER':'livedb_user',
        'PASSWORD': 'Kc@410/69',
        'HOST': '65.1.177.181',
        'PORT': '3306',
        'OPTIONS': {
        'connect_timeout': 28000,  # Increase timeout to 28 seconds            
        'sql_mode': 'traditional',
        'init_command': 'ALTER DATABASE iihmr_test CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci',
        },
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


STATIC_URL = '/static/'

STATICFILES_DIRS =[
    os.path.join(BASE_DIR,'static')
]
    
STATIC_ROOT = os.path.join(BASE_DIR,'assets')

# Base directory
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# settings.py
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'


# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

#SESSION TIMEOUT
SESSION_COOKIE_AGE = 1800
SESSION_EXPIRE_SECONDS = 1800
SESSION_EXPIRE_AFTER_LAST_ACTIVITY = True
#SESSION_ENGINE = "django.contrib.sessions.backends.cache"

# ✅ Enable credentials if using authentication (Cookies, JWT, Sessions)
CORS_ALLOW_CREDENTIALS = True

# ✅ REMOVE CORS_ALLOW_ALL_ORIGINS (Because CORS_ALLOWED_ORIGINS is used)
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "https://iihmr.test.web.kavinsoft.in",
    "https://iihmr.test.api.kavinsoft.in",
    # "https://api.iihmrbangalore.in",
    # "https://iihmrbangalore.in",
]

# Celery Configuration Options 
# Celery settings for Django

# localhost configuration for testing local redis server
# CELERY_BROKER_URL = 'redis://localhost:6379/0'  # Redis as broker
# CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'  # Redis as result backend

# Internal IPs or domain name configuration
# CELERY_BROKER_URL = 'redis://
CELERY_BROKER_URL = 'redis://192.168.137.189:6380/0'
CELERY_RESULT_BACKEND = 'redis://192.168.137.189:6380/0'

# Server IP or domain name configuration 
# # # CELERY_BROKER_URL = 'redis://
# CELERY_BROKER_URL = 'redis://iihmr.test.api.kavinsoft.in:6379/0'
# CELERY_RESULT_BACKEND = 'redis://iihmr.test.api.kavinsoft.in:6379/0'


CELERY_TASK_IGNORE_RESULT = False
CELERY_TASK_STORE_ERRORS_EVEN_IF_IGNORED = True
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
